blank_issues_enabled: false # Disable creating issues without a template
contact_links:
  - name: ğŸ› Bug Report
    url: https://github.com/ragibasif/dotfiles/issues/new?template=bug_report.md
    about: Report a bug or unexpected behavior.
  - name: ğŸš€ Feature Request
    url: https://github.com/ragibasif/dotfiles/issues/new?template=feature_request.md
    about: Suggest an idea or new feature.
  - name: â“ Questions and Help
    url: https://github.com/ragibasif/dotfiles/discussions
    about: Ask questions or get help from the community.
